### 1. Register DBlocker
POST http://localhost:3003/api/dblockers
Content-Type: application/json

{
    "name": "Drone Blocker timur",
    "serial_numb": "STM-1001",
    "latitude": -7.788432918834558,
    "longitude": 110.44306970000933,
    "desc": "Drone blocker di timur",
    "angle_start": 0,
    "config": [
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true}
    ]
}


# {
#     "name": "Drone Blocker Barat",
#     "serial_numb": "SCM-1002",
#     "latitude": -7.786959801210232,
#     "longitude": 110.4220920495705,
#     "desc": "Drone blocker di barat",
#     "angle_start": 0,
#     "config": [
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true}
#     ]
# }

### 2. Get All DBlockers
GET http://localhost:3003/api/dblockers

### 3. Get DBlocker by ID
GET http://localhost:3003/api/dblockers/1

### 4. Update DBlocker by ID
PUT http://localhost:3003/api/dblockers/6
Content-Type: application/json

{
    "name": "Drone Blocker timur",
    "serial_numb": "STM-1001",
    "latitude": -7.788432918834558,
    "longitude": 110.44306970000933,
    "desc": "Drone blocker di timur",
    "angle_start": 0,
    "config": [
        {"signal_ctrl": true, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": true}
    ]
}

# {
#     "name": "Drone Blocker Barat",
#     "serial_numb": "SCM-1002",
#     "latitude": -7.7869597,
#     "longitude": 110.4220920495705,
#     "desc": "Drone blocker di barat",
#     "angle_start": 0,
#     "config": [
#         {"signal_ctrl": false, "signal_gps": false},
#         {"signal_ctrl": false, "signal_gps": false},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": true},
#         {"signal_ctrl": true, "signal_gps": false}
#     ]
# }


### 5. Delete DBlocker by ID
DELETE http://localhost:3003/api/dblockers/8


### 6. Update DBlocker Config
PUT http://localhost:3003/api/dblockers/config
Content-Type: application/json

{
    "id": 6,
    "config": [
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": false}
    ]
}