### 1. Register DBlocker
POST http://localhost:3003/api/dblockers
Content-Type: application/json

{
    "name": "Drone Blocker timur",
    "serial_numb": "1000",
    "latitude": -7.89,
    "longitude": 110.034,
    "desc": "Drone blocker di timur",
    "angle_start": 45,
    "config": [
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true}
    ]
}

### 2. Get All DBlockers
GET http://localhost:3003/api/dblockers

### 3. Get DBlocker by ID
GET http://localhost:3003/api/dblockers/1

### 4. Update DBlocker by ID
PUT http://localhost:3003/api/dblockers/1
Content-Type: application/json

{
    "name": "Drone Blocker timur updated",
    "serial_numb": "1000",
    "latitude": -7.89714275152239,
    "longitude": 110.03435936894792,
    "desc": "Drone blocker di timur updated",
    "angle_start": 90,
    "config": [
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": false, "signal_gps": false},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true},
        {"signal_ctrl": true, "signal_gps": true}
    ]
}

### 5. Delete DBlocker by ID
DELETE http://localhost:3003/api/dblockers/3