### 1. Register a new device
POST http://localhost:5000/devices
Content-Type: application/json

{
    "name": "Drone Blocker Barat",
    "type": "jammer",
    "ip_address": "localhost:3003",
    "latitude": -7.7500,
    "longitude": 101.0000,
    "description": "Drone blocker di Barat"
}

### 2. Get All Devices
GET http://localhost:5000/devices